apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-06-29T16:36:24Z"
  labels:
    run: demo-pod1
  name: demo-pod1
  namespace: default
  resourceVersion: "16533"
  uid: 265ebadd-7ac6-4b10-8951-403deab0976f
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: demo-pod1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n5plq
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: minikube
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-n5plq
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T16:36:24Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T16:36:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T16:36:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-06-29T16:36:24Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://44480efb2d3aaf6c794368fbea85534a7fc7c9eab6af0841b05be613dc87579c
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:ec4ed8b5299e5e90694af7750eb6dffd2627317d30544d056b0371f8082f7bce
    lastState: {}
    name: demo-pod1
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-06-29T16:36:26Z"
  hostIP: 192.168.49.2
  phase: Running
  podIP: 10.244.0.39
  podIPs:
  - ip: 10.244.0.39
  qosClass: BestEffort
  startTime: "2026-06-29T16:36:24Z"
