apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-adv
  labels:
    app: nignx
    tier: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
       - containerPort: 80
    - name: checker
      image: busybox
      command: ["sh echo checker is running"]